(cl:in-package cl_msgs-msg)
(cl:export '(GEARPOSITION_LF-VAL
          GEARPOSITION_LF
          GEARPOSITION_RF-VAL
          GEARPOSITION_RF
          GEARPOSITION_LR-VAL
          GEARPOSITION_LR
          GEARPOSITION_RR-VAL
          GEARPOSITION_RR
          VCU_LIFE_SIGNAL-VAL
          VCU_LIFE_SIGNAL
          VCU_MODE-VAL
          VCU_MODE
          EPB_STATUS-VAL
          EPB_STATUS
          IPC_STATUS-VAL
          IPC_STATUS
          HARDWARE_ERROR_LEVEL-VAL
          HARDWARE_ERROR_LEVEL
          REMOTECONTROLLER_STATUS-VAL
          REMOTECONTROLLER_STATUS
          SES_F_EN_STATUS-VAL
          SES_F_EN_STATUS
          SES_R_EN_STATUS-VAL
          SES_R_EN_STATUS
          DBS_STATUS-VAL
          DBS_STATUS
          PRESSURE-VAL
          PRESSURE
          SES_F_ERROR_LEVEL-VAL
          SES_F_ERROR_LEVEL
          SES_R_ERROR_LEVEL-VAL
          SES_R_ERROR_LEVEL
          BMS_ERROR-VAL
          BMS_ERROR
          DCDC_ERROR-VAL
          DCDC_ERROR
          EPB_ERROR-VAL
          EPB_ERROR
          DBS_ERRORCODE-VAL
          DBS_ERRORCODE
))