(cl:in-package cl_msgs-msg)
(cl:export '(LF_RPM-VAL
          LF_RPM
          RF_RPM-VAL
          RF_RPM
          LR_RPM-VAL
          LR_RPM
          RR_RPM-VAL
          RR_RPM
          LF_MOTOR_GEAR-VAL
          LF_MOTOR_GEAR
          RF_MOTOR_GEAR-VAL
          RF_MOTOR_GEAR
          LR_MOTOR_GEAR-VAL
          LR_MOTOR_GEAR
          RR_MOTOR_GEAR-VAL
          RR_MOTOR_GEAR
          LF_MOTOR_EN-VAL
          LF_MOTOR_EN
          RF_MOTOR_EN-VAL
          RF_MOTOR_EN
          LR_MOTOR_EN-VAL
          LR_MOTOR_EN
          RR_MOTOR_EN-VAL
          RR_MOTOR_EN
          LF_MOTOR_BRAKE-VAL
          LF_MOTOR_BRAKE
          RF_MOTOR_BRAKE-VAL
          RF_MOTOR_BRAKE
          LR_MOTOR_BRAKE-VAL
          LR_MOTOR_BRAKE
          RR_MOTOR_BRAKE-VAL
          RR_MOTOR_BRAKE
          TARGET_BRK_PRESS-VAL
          TARGET_BRK_PRESS
          TARGET_STEER_F-VAL
          TARGET_STEER_F
          TARGET_STEER_F_EN-VAL
          TARGET_STEER_F_EN
          TARGET_STEER_R-VAL
          TARGET_STEER_R
          TARGET_STEER_R_EN-VAL
          TARGET_STEER_R_EN
          EPB_SWITCH-VAL
          EPB_SWITCH
          TARGET_MODE-VAL
          TARGET_MODE
))