// Generated by gencpp from file styx_msgs/model.msg
// DO NOT EDIT!


#ifndef STYX_MSGS_MESSAGE_MODEL_H
#define STYX_MSGS_MESSAGE_MODEL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace styx_msgs
{
template <class ContainerAllocator>
struct model_
{
  typedef model_<ContainerAllocator> Type;

  model_()
    : a(0)  {
    }
  model_(const ContainerAllocator& _alloc)
    : a(0)  {
  (void)_alloc;
    }



   typedef int32_t _a_type;
  _a_type a;





  typedef boost::shared_ptr< ::styx_msgs::model_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::styx_msgs::model_<ContainerAllocator> const> ConstPtr;

}; // struct model_

typedef ::styx_msgs::model_<std::allocator<void> > model;

typedef boost::shared_ptr< ::styx_msgs::model > modelPtr;
typedef boost::shared_ptr< ::styx_msgs::model const> modelConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::styx_msgs::model_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::styx_msgs::model_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::styx_msgs::model_<ContainerAllocator1> & lhs, const ::styx_msgs::model_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::styx_msgs::model_<ContainerAllocator1> & lhs, const ::styx_msgs::model_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace styx_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::styx_msgs::model_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::styx_msgs::model_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::styx_msgs::model_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::styx_msgs::model_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::styx_msgs::model_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::styx_msgs::model_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::styx_msgs::model_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5c9fb1a886e81e3162a5c87bf55c072b";
  }

  static const char* value(const ::styx_msgs::model_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5c9fb1a886e81e31ULL;
  static const uint64_t static_value2 = 0x62a5c87bf55c072bULL;
};

template<class ContainerAllocator>
struct DataType< ::styx_msgs::model_<ContainerAllocator> >
{
  static const char* value()
  {
    return "styx_msgs/model";
  }

  static const char* value(const ::styx_msgs::model_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::styx_msgs::model_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 a\n"
;
  }

  static const char* value(const ::styx_msgs::model_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::styx_msgs::model_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct model_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::styx_msgs::model_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::styx_msgs::model_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<int32_t>::stream(s, indent + "  ", v.a);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STYX_MSGS_MESSAGE_MODEL_H
