// Generated by gencpp from file styx_msgs/Position.msg
// DO NOT EDIT!


#ifndef STYX_MSGS_MESSAGE_POSITION_H
#define STYX_MSGS_MESSAGE_POSITION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace styx_msgs
{
template <class ContainerAllocator>
struct Position_
{
  typedef Position_<ContainerAllocator> Type;

  Position_()
    : latitude(0.0)
    , longitude(0.0)
    , yaw(0.0)  {
    }
  Position_(const ContainerAllocator& _alloc)
    : latitude(0.0)
    , longitude(0.0)
    , yaw(0.0)  {
  (void)_alloc;
    }



   typedef double _latitude_type;
  _latitude_type latitude;

   typedef double _longitude_type;
  _longitude_type longitude;

   typedef double _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::styx_msgs::Position_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::styx_msgs::Position_<ContainerAllocator> const> ConstPtr;

}; // struct Position_

typedef ::styx_msgs::Position_<std::allocator<void> > Position;

typedef boost::shared_ptr< ::styx_msgs::Position > PositionPtr;
typedef boost::shared_ptr< ::styx_msgs::Position const> PositionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::styx_msgs::Position_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::styx_msgs::Position_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::styx_msgs::Position_<ContainerAllocator1> & lhs, const ::styx_msgs::Position_<ContainerAllocator2> & rhs)
{
  return lhs.latitude == rhs.latitude &&
    lhs.longitude == rhs.longitude &&
    lhs.yaw == rhs.yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::styx_msgs::Position_<ContainerAllocator1> & lhs, const ::styx_msgs::Position_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace styx_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::styx_msgs::Position_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::styx_msgs::Position_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::styx_msgs::Position_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::styx_msgs::Position_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::styx_msgs::Position_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::styx_msgs::Position_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::styx_msgs::Position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1eb7a48b066869c948b4808bcc575127";
  }

  static const char* value(const ::styx_msgs::Position_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1eb7a48b066869c9ULL;
  static const uint64_t static_value2 = 0x48b4808bcc575127ULL;
};

template<class ContainerAllocator>
struct DataType< ::styx_msgs::Position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "styx_msgs/Position";
  }

  static const char* value(const ::styx_msgs::Position_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::styx_msgs::Position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 latitude\n"
"float64 longitude\n"
"float64 yaw\n"
;
  }

  static const char* value(const ::styx_msgs::Position_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::styx_msgs::Position_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.latitude);
      stream.next(m.longitude);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Position_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::styx_msgs::Position_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::styx_msgs::Position_<ContainerAllocator>& v)
  {
    s << indent << "latitude: ";
    Printer<double>::stream(s, indent + "  ", v.latitude);
    s << indent << "longitude: ";
    Printer<double>::stream(s, indent + "  ", v.longitude);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STYX_MSGS_MESSAGE_POSITION_H
