// Generated by gencpp from file styx_msgs/uwb.msg
// DO NOT EDIT!


#ifndef STYX_MSGS_MESSAGE_UWB_H
#define STYX_MSGS_MESSAGE_UWB_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Pose.h>

namespace styx_msgs
{
template <class ContainerAllocator>
struct uwb_
{
  typedef uwb_<ContainerAllocator> Type;

  uwb_()
    : header()
    , pose()
    , distance0(0.0)
    , distance1(0.0)
    , distance2(0.0)  {
    }
  uwb_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , pose(_alloc)
    , distance0(0.0)
    , distance1(0.0)
    , distance2(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef float _distance0_type;
  _distance0_type distance0;

   typedef float _distance1_type;
  _distance1_type distance1;

   typedef float _distance2_type;
  _distance2_type distance2;





  typedef boost::shared_ptr< ::styx_msgs::uwb_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::styx_msgs::uwb_<ContainerAllocator> const> ConstPtr;

}; // struct uwb_

typedef ::styx_msgs::uwb_<std::allocator<void> > uwb;

typedef boost::shared_ptr< ::styx_msgs::uwb > uwbPtr;
typedef boost::shared_ptr< ::styx_msgs::uwb const> uwbConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::styx_msgs::uwb_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::styx_msgs::uwb_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::styx_msgs::uwb_<ContainerAllocator1> & lhs, const ::styx_msgs::uwb_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.pose == rhs.pose &&
    lhs.distance0 == rhs.distance0 &&
    lhs.distance1 == rhs.distance1 &&
    lhs.distance2 == rhs.distance2;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::styx_msgs::uwb_<ContainerAllocator1> & lhs, const ::styx_msgs::uwb_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace styx_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::styx_msgs::uwb_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::styx_msgs::uwb_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::styx_msgs::uwb_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::styx_msgs::uwb_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::styx_msgs::uwb_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::styx_msgs::uwb_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::styx_msgs::uwb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "100136466d037274d5e51cedbebd7e9f";
  }

  static const char* value(const ::styx_msgs::uwb_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x100136466d037274ULL;
  static const uint64_t static_value2 = 0xd5e51cedbebd7e9fULL;
};

template<class ContainerAllocator>
struct DataType< ::styx_msgs::uwb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "styx_msgs/uwb";
  }

  static const char* value(const ::styx_msgs::uwb_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::styx_msgs::uwb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"geometry_msgs/Pose pose\n"
"float32 distance0\n"
"float32 distance1\n"
"float32 distance2\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::styx_msgs::uwb_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::styx_msgs::uwb_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.pose);
      stream.next(m.distance0);
      stream.next(m.distance1);
      stream.next(m.distance2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct uwb_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::styx_msgs::uwb_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::styx_msgs::uwb_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "distance0: ";
    Printer<float>::stream(s, indent + "  ", v.distance0);
    s << indent << "distance1: ";
    Printer<float>::stream(s, indent + "  ", v.distance1);
    s << indent << "distance2: ";
    Printer<float>::stream(s, indent + "  ", v.distance2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STYX_MSGS_MESSAGE_UWB_H
