# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from cl_msgs/control2.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class control2(genpy.Message):
  _md5sum = "02be7a927824000275f436c65ca9b8d0"
  _type = "cl_msgs/control2"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 Target_Brk_Press
uint16 Target_Steer_F
uint8 Target_Steer_F_En
uint16 Target_Steer_R
uint8 Target_Steer_R_En
uint8 EPB_Switch
uint8 Target_Mode
"""
  __slots__ = ['Target_Brk_Press','Target_Steer_F','Target_Steer_F_En','Target_Steer_R','Target_Steer_R_En','EPB_Switch','Target_Mode']
  _slot_types = ['float32','uint16','uint8','uint16','uint8','uint8','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       Target_Brk_Press,Target_Steer_F,Target_Steer_F_En,Target_Steer_R,Target_Steer_R_En,EPB_Switch,Target_Mode

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(control2, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.Target_Brk_Press is None:
        self.Target_Brk_Press = 0.
      if self.Target_Steer_F is None:
        self.Target_Steer_F = 0
      if self.Target_Steer_F_En is None:
        self.Target_Steer_F_En = 0
      if self.Target_Steer_R is None:
        self.Target_Steer_R = 0
      if self.Target_Steer_R_En is None:
        self.Target_Steer_R_En = 0
      if self.EPB_Switch is None:
        self.EPB_Switch = 0
      if self.Target_Mode is None:
        self.Target_Mode = 0
    else:
      self.Target_Brk_Press = 0.
      self.Target_Steer_F = 0
      self.Target_Steer_F_En = 0
      self.Target_Steer_R = 0
      self.Target_Steer_R_En = 0
      self.EPB_Switch = 0
      self.Target_Mode = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_fHBH3B().pack(_x.Target_Brk_Press, _x.Target_Steer_F, _x.Target_Steer_F_En, _x.Target_Steer_R, _x.Target_Steer_R_En, _x.EPB_Switch, _x.Target_Mode))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.Target_Brk_Press, _x.Target_Steer_F, _x.Target_Steer_F_En, _x.Target_Steer_R, _x.Target_Steer_R_En, _x.EPB_Switch, _x.Target_Mode,) = _get_struct_fHBH3B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_fHBH3B().pack(_x.Target_Brk_Press, _x.Target_Steer_F, _x.Target_Steer_F_En, _x.Target_Steer_R, _x.Target_Steer_R_En, _x.EPB_Switch, _x.Target_Mode))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.Target_Brk_Press, _x.Target_Steer_F, _x.Target_Steer_F_En, _x.Target_Steer_R, _x.Target_Steer_R_En, _x.EPB_Switch, _x.Target_Mode,) = _get_struct_fHBH3B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_fHBH3B = None
def _get_struct_fHBH3B():
    global _struct_fHBH3B
    if _struct_fHBH3B is None:
        _struct_fHBH3B = struct.Struct("<fHBH3B")
    return _struct_fHBH3B
