// Generated by gencpp from file cl_msgs/control3.msg
// DO NOT EDIT!


#ifndef CL_MSGS_MESSAGE_CONTROL3_H
#define CL_MSGS_MESSAGE_CONTROL3_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cl_msgs
{
template <class ContainerAllocator>
struct control3_
{
  typedef control3_<ContainerAllocator> Type;

  control3_()
    : LF_Rpm(0)
    , RF_Rpm(0)
    , LR_Rpm(0)
    , RR_Rpm(0)
    , LF_Motor_Gear(0)
    , RF_Motor_Gear(0)
    , LR_Motor_Gear(0)
    , RR_Motor_Gear(0)
    , LF_Motor_En(0)
    , RF_Motor_En(0)
    , LR_Motor_En(0)
    , RR_Motor_En(0)
    , LF_Motor_Brake(0)
    , RF_Motor_Brake(0)
    , LR_Motor_Brake(0)
    , RR_Motor_Brake(0)
    , Target_Brk_Press(0.0)
    , Target_Steer_F(0)
    , Target_Steer_F_En(0)
    , Target_Steer_R(0)
    , Target_Steer_R_En(0)
    , EPB_Switch(0)
    , Target_Mode(0)  {
    }
  control3_(const ContainerAllocator& _alloc)
    : LF_Rpm(0)
    , RF_Rpm(0)
    , LR_Rpm(0)
    , RR_Rpm(0)
    , LF_Motor_Gear(0)
    , RF_Motor_Gear(0)
    , LR_Motor_Gear(0)
    , RR_Motor_Gear(0)
    , LF_Motor_En(0)
    , RF_Motor_En(0)
    , LR_Motor_En(0)
    , RR_Motor_En(0)
    , LF_Motor_Brake(0)
    , RF_Motor_Brake(0)
    , LR_Motor_Brake(0)
    , RR_Motor_Brake(0)
    , Target_Brk_Press(0.0)
    , Target_Steer_F(0)
    , Target_Steer_F_En(0)
    , Target_Steer_R(0)
    , Target_Steer_R_En(0)
    , EPB_Switch(0)
    , Target_Mode(0)  {
  (void)_alloc;
    }



   typedef uint16_t _LF_Rpm_type;
  _LF_Rpm_type LF_Rpm;

   typedef uint16_t _RF_Rpm_type;
  _RF_Rpm_type RF_Rpm;

   typedef uint16_t _LR_Rpm_type;
  _LR_Rpm_type LR_Rpm;

   typedef uint16_t _RR_Rpm_type;
  _RR_Rpm_type RR_Rpm;

   typedef uint8_t _LF_Motor_Gear_type;
  _LF_Motor_Gear_type LF_Motor_Gear;

   typedef uint8_t _RF_Motor_Gear_type;
  _RF_Motor_Gear_type RF_Motor_Gear;

   typedef uint8_t _LR_Motor_Gear_type;
  _LR_Motor_Gear_type LR_Motor_Gear;

   typedef uint8_t _RR_Motor_Gear_type;
  _RR_Motor_Gear_type RR_Motor_Gear;

   typedef uint8_t _LF_Motor_En_type;
  _LF_Motor_En_type LF_Motor_En;

   typedef uint8_t _RF_Motor_En_type;
  _RF_Motor_En_type RF_Motor_En;

   typedef uint8_t _LR_Motor_En_type;
  _LR_Motor_En_type LR_Motor_En;

   typedef uint8_t _RR_Motor_En_type;
  _RR_Motor_En_type RR_Motor_En;

   typedef uint8_t _LF_Motor_Brake_type;
  _LF_Motor_Brake_type LF_Motor_Brake;

   typedef uint8_t _RF_Motor_Brake_type;
  _RF_Motor_Brake_type RF_Motor_Brake;

   typedef uint8_t _LR_Motor_Brake_type;
  _LR_Motor_Brake_type LR_Motor_Brake;

   typedef uint8_t _RR_Motor_Brake_type;
  _RR_Motor_Brake_type RR_Motor_Brake;

   typedef float _Target_Brk_Press_type;
  _Target_Brk_Press_type Target_Brk_Press;

   typedef uint16_t _Target_Steer_F_type;
  _Target_Steer_F_type Target_Steer_F;

   typedef uint8_t _Target_Steer_F_En_type;
  _Target_Steer_F_En_type Target_Steer_F_En;

   typedef uint16_t _Target_Steer_R_type;
  _Target_Steer_R_type Target_Steer_R;

   typedef uint8_t _Target_Steer_R_En_type;
  _Target_Steer_R_En_type Target_Steer_R_En;

   typedef uint8_t _EPB_Switch_type;
  _EPB_Switch_type EPB_Switch;

   typedef uint8_t _Target_Mode_type;
  _Target_Mode_type Target_Mode;





  typedef boost::shared_ptr< ::cl_msgs::control3_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cl_msgs::control3_<ContainerAllocator> const> ConstPtr;

}; // struct control3_

typedef ::cl_msgs::control3_<std::allocator<void> > control3;

typedef boost::shared_ptr< ::cl_msgs::control3 > control3Ptr;
typedef boost::shared_ptr< ::cl_msgs::control3 const> control3ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cl_msgs::control3_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cl_msgs::control3_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cl_msgs::control3_<ContainerAllocator1> & lhs, const ::cl_msgs::control3_<ContainerAllocator2> & rhs)
{
  return lhs.LF_Rpm == rhs.LF_Rpm &&
    lhs.RF_Rpm == rhs.RF_Rpm &&
    lhs.LR_Rpm == rhs.LR_Rpm &&
    lhs.RR_Rpm == rhs.RR_Rpm &&
    lhs.LF_Motor_Gear == rhs.LF_Motor_Gear &&
    lhs.RF_Motor_Gear == rhs.RF_Motor_Gear &&
    lhs.LR_Motor_Gear == rhs.LR_Motor_Gear &&
    lhs.RR_Motor_Gear == rhs.RR_Motor_Gear &&
    lhs.LF_Motor_En == rhs.LF_Motor_En &&
    lhs.RF_Motor_En == rhs.RF_Motor_En &&
    lhs.LR_Motor_En == rhs.LR_Motor_En &&
    lhs.RR_Motor_En == rhs.RR_Motor_En &&
    lhs.LF_Motor_Brake == rhs.LF_Motor_Brake &&
    lhs.RF_Motor_Brake == rhs.RF_Motor_Brake &&
    lhs.LR_Motor_Brake == rhs.LR_Motor_Brake &&
    lhs.RR_Motor_Brake == rhs.RR_Motor_Brake &&
    lhs.Target_Brk_Press == rhs.Target_Brk_Press &&
    lhs.Target_Steer_F == rhs.Target_Steer_F &&
    lhs.Target_Steer_F_En == rhs.Target_Steer_F_En &&
    lhs.Target_Steer_R == rhs.Target_Steer_R &&
    lhs.Target_Steer_R_En == rhs.Target_Steer_R_En &&
    lhs.EPB_Switch == rhs.EPB_Switch &&
    lhs.Target_Mode == rhs.Target_Mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cl_msgs::control3_<ContainerAllocator1> & lhs, const ::cl_msgs::control3_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cl_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::cl_msgs::control3_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cl_msgs::control3_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cl_msgs::control3_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cl_msgs::control3_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cl_msgs::control3_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cl_msgs::control3_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cl_msgs::control3_<ContainerAllocator> >
{
  static const char* value()
  {
    return "97f59ffa6578ff05e846f79c2eb2217c";
  }

  static const char* value(const ::cl_msgs::control3_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x97f59ffa6578ff05ULL;
  static const uint64_t static_value2 = 0xe846f79c2eb2217cULL;
};

template<class ContainerAllocator>
struct DataType< ::cl_msgs::control3_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cl_msgs/control3";
  }

  static const char* value(const ::cl_msgs::control3_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cl_msgs::control3_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 LF_Rpm\n"
"uint16 RF_Rpm\n"
"uint16 LR_Rpm\n"
"uint16 RR_Rpm\n"
"uint8 LF_Motor_Gear\n"
"uint8 RF_Motor_Gear\n"
"uint8 LR_Motor_Gear\n"
"uint8 RR_Motor_Gear\n"
"uint8 LF_Motor_En\n"
"uint8 RF_Motor_En\n"
"uint8 LR_Motor_En\n"
"uint8 RR_Motor_En\n"
"uint8 LF_Motor_Brake\n"
"uint8 RF_Motor_Brake\n"
"uint8 LR_Motor_Brake\n"
"uint8 RR_Motor_Brake\n"
"\n"
"float32 Target_Brk_Press\n"
"uint16 Target_Steer_F\n"
"uint8 Target_Steer_F_En\n"
"uint16 Target_Steer_R\n"
"uint8 Target_Steer_R_En\n"
"uint8 EPB_Switch\n"
"uint8 Target_Mode\n"
;
  }

  static const char* value(const ::cl_msgs::control3_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cl_msgs::control3_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.LF_Rpm);
      stream.next(m.RF_Rpm);
      stream.next(m.LR_Rpm);
      stream.next(m.RR_Rpm);
      stream.next(m.LF_Motor_Gear);
      stream.next(m.RF_Motor_Gear);
      stream.next(m.LR_Motor_Gear);
      stream.next(m.RR_Motor_Gear);
      stream.next(m.LF_Motor_En);
      stream.next(m.RF_Motor_En);
      stream.next(m.LR_Motor_En);
      stream.next(m.RR_Motor_En);
      stream.next(m.LF_Motor_Brake);
      stream.next(m.RF_Motor_Brake);
      stream.next(m.LR_Motor_Brake);
      stream.next(m.RR_Motor_Brake);
      stream.next(m.Target_Brk_Press);
      stream.next(m.Target_Steer_F);
      stream.next(m.Target_Steer_F_En);
      stream.next(m.Target_Steer_R);
      stream.next(m.Target_Steer_R_En);
      stream.next(m.EPB_Switch);
      stream.next(m.Target_Mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct control3_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cl_msgs::control3_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cl_msgs::control3_<ContainerAllocator>& v)
  {
    s << indent << "LF_Rpm: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.LF_Rpm);
    s << indent << "RF_Rpm: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.RF_Rpm);
    s << indent << "LR_Rpm: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.LR_Rpm);
    s << indent << "RR_Rpm: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.RR_Rpm);
    s << indent << "LF_Motor_Gear: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.LF_Motor_Gear);
    s << indent << "RF_Motor_Gear: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.RF_Motor_Gear);
    s << indent << "LR_Motor_Gear: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.LR_Motor_Gear);
    s << indent << "RR_Motor_Gear: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.RR_Motor_Gear);
    s << indent << "LF_Motor_En: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.LF_Motor_En);
    s << indent << "RF_Motor_En: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.RF_Motor_En);
    s << indent << "LR_Motor_En: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.LR_Motor_En);
    s << indent << "RR_Motor_En: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.RR_Motor_En);
    s << indent << "LF_Motor_Brake: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.LF_Motor_Brake);
    s << indent << "RF_Motor_Brake: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.RF_Motor_Brake);
    s << indent << "LR_Motor_Brake: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.LR_Motor_Brake);
    s << indent << "RR_Motor_Brake: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.RR_Motor_Brake);
    s << indent << "Target_Brk_Press: ";
    Printer<float>::stream(s, indent + "  ", v.Target_Brk_Press);
    s << indent << "Target_Steer_F: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.Target_Steer_F);
    s << indent << "Target_Steer_F_En: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Target_Steer_F_En);
    s << indent << "Target_Steer_R: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.Target_Steer_R);
    s << indent << "Target_Steer_R_En: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Target_Steer_R_En);
    s << indent << "EPB_Switch: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.EPB_Switch);
    s << indent << "Target_Mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Target_Mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CL_MSGS_MESSAGE_CONTROL3_H
