// Generated by gencpp from file cl_msgs/control2.msg
// DO NOT EDIT!


#ifndef CL_MSGS_MESSAGE_CONTROL2_H
#define CL_MSGS_MESSAGE_CONTROL2_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cl_msgs
{
template <class ContainerAllocator>
struct control2_
{
  typedef control2_<ContainerAllocator> Type;

  control2_()
    : Target_Brk_Press(0.0)
    , Target_Steer_F(0)
    , Target_Steer_F_En(0)
    , Target_Steer_R(0)
    , Target_Steer_R_En(0)
    , EPB_Switch(0)
    , Target_Mode(0)  {
    }
  control2_(const ContainerAllocator& _alloc)
    : Target_Brk_Press(0.0)
    , Target_Steer_F(0)
    , Target_Steer_F_En(0)
    , Target_Steer_R(0)
    , Target_Steer_R_En(0)
    , EPB_Switch(0)
    , Target_Mode(0)  {
  (void)_alloc;
    }



   typedef float _Target_Brk_Press_type;
  _Target_Brk_Press_type Target_Brk_Press;

   typedef uint16_t _Target_Steer_F_type;
  _Target_Steer_F_type Target_Steer_F;

   typedef uint8_t _Target_Steer_F_En_type;
  _Target_Steer_F_En_type Target_Steer_F_En;

   typedef uint16_t _Target_Steer_R_type;
  _Target_Steer_R_type Target_Steer_R;

   typedef uint8_t _Target_Steer_R_En_type;
  _Target_Steer_R_En_type Target_Steer_R_En;

   typedef uint8_t _EPB_Switch_type;
  _EPB_Switch_type EPB_Switch;

   typedef uint8_t _Target_Mode_type;
  _Target_Mode_type Target_Mode;





  typedef boost::shared_ptr< ::cl_msgs::control2_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cl_msgs::control2_<ContainerAllocator> const> ConstPtr;

}; // struct control2_

typedef ::cl_msgs::control2_<std::allocator<void> > control2;

typedef boost::shared_ptr< ::cl_msgs::control2 > control2Ptr;
typedef boost::shared_ptr< ::cl_msgs::control2 const> control2ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cl_msgs::control2_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cl_msgs::control2_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cl_msgs::control2_<ContainerAllocator1> & lhs, const ::cl_msgs::control2_<ContainerAllocator2> & rhs)
{
  return lhs.Target_Brk_Press == rhs.Target_Brk_Press &&
    lhs.Target_Steer_F == rhs.Target_Steer_F &&
    lhs.Target_Steer_F_En == rhs.Target_Steer_F_En &&
    lhs.Target_Steer_R == rhs.Target_Steer_R &&
    lhs.Target_Steer_R_En == rhs.Target_Steer_R_En &&
    lhs.EPB_Switch == rhs.EPB_Switch &&
    lhs.Target_Mode == rhs.Target_Mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cl_msgs::control2_<ContainerAllocator1> & lhs, const ::cl_msgs::control2_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cl_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::cl_msgs::control2_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cl_msgs::control2_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cl_msgs::control2_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cl_msgs::control2_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cl_msgs::control2_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cl_msgs::control2_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cl_msgs::control2_<ContainerAllocator> >
{
  static const char* value()
  {
    return "02be7a927824000275f436c65ca9b8d0";
  }

  static const char* value(const ::cl_msgs::control2_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x02be7a9278240002ULL;
  static const uint64_t static_value2 = 0x75f436c65ca9b8d0ULL;
};

template<class ContainerAllocator>
struct DataType< ::cl_msgs::control2_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cl_msgs/control2";
  }

  static const char* value(const ::cl_msgs::control2_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cl_msgs::control2_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 Target_Brk_Press\n"
"uint16 Target_Steer_F\n"
"uint8 Target_Steer_F_En\n"
"uint16 Target_Steer_R\n"
"uint8 Target_Steer_R_En\n"
"uint8 EPB_Switch\n"
"uint8 Target_Mode\n"
;
  }

  static const char* value(const ::cl_msgs::control2_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cl_msgs::control2_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Target_Brk_Press);
      stream.next(m.Target_Steer_F);
      stream.next(m.Target_Steer_F_En);
      stream.next(m.Target_Steer_R);
      stream.next(m.Target_Steer_R_En);
      stream.next(m.EPB_Switch);
      stream.next(m.Target_Mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct control2_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cl_msgs::control2_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cl_msgs::control2_<ContainerAllocator>& v)
  {
    s << indent << "Target_Brk_Press: ";
    Printer<float>::stream(s, indent + "  ", v.Target_Brk_Press);
    s << indent << "Target_Steer_F: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.Target_Steer_F);
    s << indent << "Target_Steer_F_En: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Target_Steer_F_En);
    s << indent << "Target_Steer_R: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.Target_Steer_R);
    s << indent << "Target_Steer_R_En: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Target_Steer_R_En);
    s << indent << "EPB_Switch: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.EPB_Switch);
    s << indent << "Target_Mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Target_Mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CL_MSGS_MESSAGE_CONTROL2_H
