// Generated by gencpp from file cl_msgs/robot_state.msg
// DO NOT EDIT!


#ifndef CL_MSGS_MESSAGE_ROBOT_STATE_H
#define CL_MSGS_MESSAGE_ROBOT_STATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cl_msgs
{
template <class ContainerAllocator>
struct robot_state_
{
  typedef robot_state_<ContainerAllocator> Type;

  robot_state_()
    : Battery_Voltage(0.0)  {
    }
  robot_state_(const ContainerAllocator& _alloc)
    : Battery_Voltage(0.0)  {
  (void)_alloc;
    }



   typedef float _Battery_Voltage_type;
  _Battery_Voltage_type Battery_Voltage;





  typedef boost::shared_ptr< ::cl_msgs::robot_state_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cl_msgs::robot_state_<ContainerAllocator> const> ConstPtr;

}; // struct robot_state_

typedef ::cl_msgs::robot_state_<std::allocator<void> > robot_state;

typedef boost::shared_ptr< ::cl_msgs::robot_state > robot_statePtr;
typedef boost::shared_ptr< ::cl_msgs::robot_state const> robot_stateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cl_msgs::robot_state_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cl_msgs::robot_state_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cl_msgs::robot_state_<ContainerAllocator1> & lhs, const ::cl_msgs::robot_state_<ContainerAllocator2> & rhs)
{
  return lhs.Battery_Voltage == rhs.Battery_Voltage;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cl_msgs::robot_state_<ContainerAllocator1> & lhs, const ::cl_msgs::robot_state_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cl_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::cl_msgs::robot_state_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cl_msgs::robot_state_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cl_msgs::robot_state_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cl_msgs::robot_state_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cl_msgs::robot_state_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cl_msgs::robot_state_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cl_msgs::robot_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "07ecd9f6cbdbd3754f8acf0447d36bfd";
  }

  static const char* value(const ::cl_msgs::robot_state_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x07ecd9f6cbdbd375ULL;
  static const uint64_t static_value2 = 0x4f8acf0447d36bfdULL;
};

template<class ContainerAllocator>
struct DataType< ::cl_msgs::robot_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cl_msgs/robot_state";
  }

  static const char* value(const ::cl_msgs::robot_state_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cl_msgs::robot_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 Battery_Voltage\n"
;
  }

  static const char* value(const ::cl_msgs::robot_state_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cl_msgs::robot_state_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Battery_Voltage);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robot_state_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cl_msgs::robot_state_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cl_msgs::robot_state_<ContainerAllocator>& v)
  {
    s << indent << "Battery_Voltage: ";
    Printer<float>::stream(s, indent + "  ", v.Battery_Voltage);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CL_MSGS_MESSAGE_ROBOT_STATE_H
