// Generated by gencpp from file cl_msgs/VCU_info_3.msg
// DO NOT EDIT!


#ifndef CL_MSGS_MESSAGE_VCU_INFO_3_H
#define CL_MSGS_MESSAGE_VCU_INFO_3_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cl_msgs
{
template <class ContainerAllocator>
struct VCU_info_3_
{
  typedef VCU_info_3_<ContainerAllocator> Type;

  VCU_info_3_()
    : Battery_Voltage(0.0)
    , SOC(0.0)
    , Battery_Current(0.0)
    , DCDC_Output_Voltage(0.0)
    , DCDC_Output_Current(0.0)  {
    }
  VCU_info_3_(const ContainerAllocator& _alloc)
    : Battery_Voltage(0.0)
    , SOC(0.0)
    , Battery_Current(0.0)
    , DCDC_Output_Voltage(0.0)
    , DCDC_Output_Current(0.0)  {
  (void)_alloc;
    }



   typedef float _Battery_Voltage_type;
  _Battery_Voltage_type Battery_Voltage;

   typedef float _SOC_type;
  _SOC_type SOC;

   typedef float _Battery_Current_type;
  _Battery_Current_type Battery_Current;

   typedef float _DCDC_Output_Voltage_type;
  _DCDC_Output_Voltage_type DCDC_Output_Voltage;

   typedef float _DCDC_Output_Current_type;
  _DCDC_Output_Current_type DCDC_Output_Current;





  typedef boost::shared_ptr< ::cl_msgs::VCU_info_3_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cl_msgs::VCU_info_3_<ContainerAllocator> const> ConstPtr;

}; // struct VCU_info_3_

typedef ::cl_msgs::VCU_info_3_<std::allocator<void> > VCU_info_3;

typedef boost::shared_ptr< ::cl_msgs::VCU_info_3 > VCU_info_3Ptr;
typedef boost::shared_ptr< ::cl_msgs::VCU_info_3 const> VCU_info_3ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cl_msgs::VCU_info_3_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cl_msgs::VCU_info_3_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cl_msgs::VCU_info_3_<ContainerAllocator1> & lhs, const ::cl_msgs::VCU_info_3_<ContainerAllocator2> & rhs)
{
  return lhs.Battery_Voltage == rhs.Battery_Voltage &&
    lhs.SOC == rhs.SOC &&
    lhs.Battery_Current == rhs.Battery_Current &&
    lhs.DCDC_Output_Voltage == rhs.DCDC_Output_Voltage &&
    lhs.DCDC_Output_Current == rhs.DCDC_Output_Current;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cl_msgs::VCU_info_3_<ContainerAllocator1> & lhs, const ::cl_msgs::VCU_info_3_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cl_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::cl_msgs::VCU_info_3_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cl_msgs::VCU_info_3_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cl_msgs::VCU_info_3_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cl_msgs::VCU_info_3_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cl_msgs::VCU_info_3_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cl_msgs::VCU_info_3_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cl_msgs::VCU_info_3_<ContainerAllocator> >
{
  static const char* value()
  {
    return "782618799da4eee77b13168565258a7f";
  }

  static const char* value(const ::cl_msgs::VCU_info_3_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x782618799da4eee7ULL;
  static const uint64_t static_value2 = 0x7b13168565258a7fULL;
};

template<class ContainerAllocator>
struct DataType< ::cl_msgs::VCU_info_3_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cl_msgs/VCU_info_3";
  }

  static const char* value(const ::cl_msgs::VCU_info_3_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cl_msgs::VCU_info_3_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 Battery_Voltage\n"
"float32 SOC\n"
"float32 Battery_Current\n"
"float32 DCDC_Output_Voltage\n"
"float32 DCDC_Output_Current\n"
;
  }

  static const char* value(const ::cl_msgs::VCU_info_3_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cl_msgs::VCU_info_3_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Battery_Voltage);
      stream.next(m.SOC);
      stream.next(m.Battery_Current);
      stream.next(m.DCDC_Output_Voltage);
      stream.next(m.DCDC_Output_Current);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VCU_info_3_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cl_msgs::VCU_info_3_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cl_msgs::VCU_info_3_<ContainerAllocator>& v)
  {
    s << indent << "Battery_Voltage: ";
    Printer<float>::stream(s, indent + "  ", v.Battery_Voltage);
    s << indent << "SOC: ";
    Printer<float>::stream(s, indent + "  ", v.SOC);
    s << indent << "Battery_Current: ";
    Printer<float>::stream(s, indent + "  ", v.Battery_Current);
    s << indent << "DCDC_Output_Voltage: ";
    Printer<float>::stream(s, indent + "  ", v.DCDC_Output_Voltage);
    s << indent << "DCDC_Output_Current: ";
    Printer<float>::stream(s, indent + "  ", v.DCDC_Output_Current);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CL_MSGS_MESSAGE_VCU_INFO_3_H
