// Generated by gencpp from file cl_msgs/VCU_info_1.msg
// DO NOT EDIT!


#ifndef CL_MSGS_MESSAGE_VCU_INFO_1_H
#define CL_MSGS_MESSAGE_VCU_INFO_1_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cl_msgs
{
template <class ContainerAllocator>
struct VCU_info_1_
{
  typedef VCU_info_1_<ContainerAllocator> Type;

  VCU_info_1_()
    : Angle_F(0.0)
    , Angle_R(0.0)
    , LF_Rpm(0)
    , RF_Rpm(0)
    , LR_Rpm(0)
    , RR_Rpm(0)  {
    }
  VCU_info_1_(const ContainerAllocator& _alloc)
    : Angle_F(0.0)
    , Angle_R(0.0)
    , LF_Rpm(0)
    , RF_Rpm(0)
    , LR_Rpm(0)
    , RR_Rpm(0)  {
  (void)_alloc;
    }



   typedef float _Angle_F_type;
  _Angle_F_type Angle_F;

   typedef float _Angle_R_type;
  _Angle_R_type Angle_R;

   typedef uint16_t _LF_Rpm_type;
  _LF_Rpm_type LF_Rpm;

   typedef uint16_t _RF_Rpm_type;
  _RF_Rpm_type RF_Rpm;

   typedef uint16_t _LR_Rpm_type;
  _LR_Rpm_type LR_Rpm;

   typedef uint16_t _RR_Rpm_type;
  _RR_Rpm_type RR_Rpm;





  typedef boost::shared_ptr< ::cl_msgs::VCU_info_1_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cl_msgs::VCU_info_1_<ContainerAllocator> const> ConstPtr;

}; // struct VCU_info_1_

typedef ::cl_msgs::VCU_info_1_<std::allocator<void> > VCU_info_1;

typedef boost::shared_ptr< ::cl_msgs::VCU_info_1 > VCU_info_1Ptr;
typedef boost::shared_ptr< ::cl_msgs::VCU_info_1 const> VCU_info_1ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cl_msgs::VCU_info_1_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cl_msgs::VCU_info_1_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cl_msgs::VCU_info_1_<ContainerAllocator1> & lhs, const ::cl_msgs::VCU_info_1_<ContainerAllocator2> & rhs)
{
  return lhs.Angle_F == rhs.Angle_F &&
    lhs.Angle_R == rhs.Angle_R &&
    lhs.LF_Rpm == rhs.LF_Rpm &&
    lhs.RF_Rpm == rhs.RF_Rpm &&
    lhs.LR_Rpm == rhs.LR_Rpm &&
    lhs.RR_Rpm == rhs.RR_Rpm;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cl_msgs::VCU_info_1_<ContainerAllocator1> & lhs, const ::cl_msgs::VCU_info_1_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cl_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::cl_msgs::VCU_info_1_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cl_msgs::VCU_info_1_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cl_msgs::VCU_info_1_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cl_msgs::VCU_info_1_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cl_msgs::VCU_info_1_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cl_msgs::VCU_info_1_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cl_msgs::VCU_info_1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "317dc21bd93b5222cd2a769eb3197f81";
  }

  static const char* value(const ::cl_msgs::VCU_info_1_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x317dc21bd93b5222ULL;
  static const uint64_t static_value2 = 0xcd2a769eb3197f81ULL;
};

template<class ContainerAllocator>
struct DataType< ::cl_msgs::VCU_info_1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cl_msgs/VCU_info_1";
  }

  static const char* value(const ::cl_msgs::VCU_info_1_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cl_msgs::VCU_info_1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 Angle_F\n"
"float32 Angle_R\n"
"uint16 LF_Rpm\n"
"uint16 RF_Rpm\n"
"uint16 LR_Rpm\n"
"uint16 RR_Rpm\n"
;
  }

  static const char* value(const ::cl_msgs::VCU_info_1_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cl_msgs::VCU_info_1_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Angle_F);
      stream.next(m.Angle_R);
      stream.next(m.LF_Rpm);
      stream.next(m.RF_Rpm);
      stream.next(m.LR_Rpm);
      stream.next(m.RR_Rpm);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VCU_info_1_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cl_msgs::VCU_info_1_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cl_msgs::VCU_info_1_<ContainerAllocator>& v)
  {
    s << indent << "Angle_F: ";
    Printer<float>::stream(s, indent + "  ", v.Angle_F);
    s << indent << "Angle_R: ";
    Printer<float>::stream(s, indent + "  ", v.Angle_R);
    s << indent << "LF_Rpm: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.LF_Rpm);
    s << indent << "RF_Rpm: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.RF_Rpm);
    s << indent << "LR_Rpm: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.LR_Rpm);
    s << indent << "RR_Rpm: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.RR_Rpm);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CL_MSGS_MESSAGE_VCU_INFO_1_H
